alter table stock
    modify sector enum ('TECHNOLOGY', 'COMMUNICATION_SERVICES', 'HEALTHCARE', 'CONSUMER_CYCLICAL', 'CONSUMER_DEFENSIVE', 'BASIC_MATERIALS', 'FINANCIAL_SERVICES', 'INDUSTRIALS', 'REAL_ESTATE', 'ENERGY', 'UTILITIES', 'INDUSTRIAL_GOODS', 'FINANCIAL', 'SERVICES', 'CONGLOMERATES', 'ETC', 'ETF') null;
